### PR TITLE
Feat: Create individual challenge (app) layout and styles

### PR DESCRIPTION
**Pull request by llandkoer**
Layout Challenge (app) [US22](https://trello.com/c/7kaGe98l/30-us22)

### CODE REVIEW

**Comment by llandkoer** [comment]
Hey guys! 

I took some advantages I had some free time today and I improve the way we had the `.gitignore` file (I added the `node_modules` folder). I also update the `styles.scss` file, so that if one of US create a branch from develop, that branch will have the minimum styles splits files added to work properly.

**Review by Jeferguto — APPROVED** [review]
Good job!

**Review by NataliaOrtizMa — APPROVED** [review]
Good job!

**Review by DuvanVilladiego — COMMENTED** [review]
no coments

**Pull request merged**
