### PR TITLE
Feat: Get and Redeem points added to Api

### PR DESCRIPTION
**Pull request by DuvanVilladiego**
[US24](https://trello.com/c/FGOYxHBO)

### CODE REVIEW

**Review by NataliaOrtizMa — APPROVED** [review]
Good job!

**Review by llandkoer — COMMENTED** [review]
Hey Duvan. Hope you are doing well. 

I have some comments about your PR.

- I know you were maybe testing the authentication routes, but it is not necessary to update the `db.json` file.

- Why did you add `path` as a new dependency if it seems like you're not using it?.

- Try to don't add any `console.log()` on the PR's. They are a good idea when you're quickly debugging your code, but They are unnecessary to have on PR's

**Comment by llandkoer** [comment]
Hey Duvan. Hope you are doing well.

I have some comments about your PR.

- Natalia did an excellent job by defining the name of the routes in a [document](https://docs.google.com/document/d/1NO42XbU7gsaVZkmspsYCobTvLOL8KPLjpM1YUzM6nzQ/edit). Please use them.

- The message, when validating if `user` exist or not on our database, should not be `Token no valid`. You're not validating the token (that is a middleware's task). I think I could be something like: `This user doest not exist on our databse`. Remember that, if you want to get the ID, you can catch from the `verifyToken` middleware (It means that you don't have to request it to the fronted, you already got it).

- Could you please give us more context: why are you catching the user's points by `req.headers.points`? What is it you suppose to get?

**Review by llandkoer — COMMENTED** [review]
Hey Duvan. Hope you are having a nice day.

I have some comments about your PR:

- `redimePoints` controller asks for `user_id`. Remember that it is better to take the `id` from the middleware.

- Remember that the message should not be `Token no valid` since you are not validating the token. That is done by the middleware.

- I know it can be difficult, but try to be careful with English typos (there are some plugins that could help you with this).

- It is very important that you do validations. Especially on methods other than GET. `express-validator` helps a lot in this task.

Finally, remember you can install `eslint` and `nodemon` globally. So that you won't have to install them in every single project you need them.

**Review by NataliaOrtizMa — COMMENTED** [review]
Try to not push `console.log( )` lines, as in `authControllers.js` file

**Review by krincon36 — APPROVED** [review]

**Review by Jeferguto — APPROVED** [review]

**Pull request merged**
