### PR TITLE
Docs: update README.md

### PR DESCRIPTION
**Pull request by llandkoer**
Hey guys! 

I had some time and decided to build and improve a bit our `README.md`. 

Let me know your comments, so we can improve it together. 

I hope you like it.

### CODE REVIEW

**Review by NataliaOrtizMa — COMMENTED** [review]
Wow, nice work! I love it!
Just some comments:

- I think the title of the `Readme` should be Amécity, with the accent mark, because it is the way it's used in the text.
- Is it possible to shrink the logo? Maybe it is too big
- In the first line, I think its better to change _pesos_ to COP
- Maybe in the `built with` section, it could be added Node.js too
- You have a typo in MondoDB, it's Mon**g**o
- Before the text, or anywhere, we can use the quote:

> “La única forma, si vamos a mejorar la calidad del medio ambiente, es involucrar a todo el mundo! - Richard Rogers

**Comment by llandkoer** [comment]
> Wow, nice work! I love it!
> Just some comments:
> 
> * I think the title of the `Readme` should be Amécity, with the accent mark, because it is the way it's used in the text.
> * Is it possible to shrink the logo? Maybe it is too big
> * In the first line, I think its better to change _pesos_ to COP
> * Maybe in the `built with` section, it could be added Node.js too
> * You have a typo in MondoDB, it's Mon**g**o
> * Before the text, or anywhere, we can use the quote:
> 
> > “La única forma, si vamos a mejorar la calidad del medio ambiente, es involucrar a todo el mundo! - Richard Rogers

**Comment by llandkoer** [comment]
Thanks, @NataliaOrtizMa . I'll take your suggestions and I'll implement them ASAP.

**Comment by DuvanVilladiego** [comment]
Nothing to comment

**Review by DuvanVilladiego — APPROVED** [review]

**Review by NataliaOrtizMa — APPROVED** [review]

**Pull request merged**
