### PR TITLE
Feat: Add forms and form action

### PR DESCRIPTION
**Pull request by NataliaOrtizMa**
Layout Suggest Challenge [US11](https://trello.com/c/dUPHYAGB)
Sugest Challenge form action [US14](https://trello.com/c/caOtf4UX)
Layout Login Form [US15](https://trello.com/c/i1qpe8I6)

### CODE REVIEW

**Review by DuvanVilladiego — COMMENTED** [review]
aproved

**Review by llandkoer — CHANGES_REQUESTED** [review]
Very good job!

Just a couple of things: 

1. Remember to use our conventions to name the files. Remember we should use English there.

2. Could you please give us more context about why are you modifying in that way some of our base styles files (`_extends.scss`, `styles.scss`)?

Finally, please take a look at my last PR. I modified some things about two of our base styles files (`_mixins.scss` and `styles.scss`)

**Comment by NataliaOrtizMa** [comment]
1. Fixed file name
2. `styles.css` modified to add `import` files, `extend.css` modified to apply `placeholder` settings

**Review by llandkoer — APPROVED** [review]
You did an excellent job!

**Comment by DuvanVilladiego** [comment]
No coments

**Review by krincon36 — APPROVED** [review]
no comment
nice job.

**Review by llandkoer — APPROVED** [review]
Well done!

**Pull request merged**
