### PR TITLE
feat: create footer app and footer static

### PR DESCRIPTION
**Pull request by DuvanVilladiego**
Layout footer [US6](https://trello.com/c/JAb62StO)

### CODE REVIEW

**Review by llandkoer — COMMENTED** [review]
Hey, Duvan! 

Just a couple of things:

- Why did you import the `variables.scss` file in that place? The Sass splits should be in the main `.scss` file, right?
- As Natalia said, remember to use REM in font sizes.

**Review by NataliaOrtizMa — COMMENTED** [review]
Just a single comment: To move from px to rem, just you had to add decimal point. For example, to change `48px`, is as easy as write `4.8rem`, because we already added the conversion rate ` font-size: 62.5%;` in the `typography.scss` file.

**Review by NataliaOrtizMa — APPROVED** [review]
Excellent!

**Review by llandkoer — APPROVED** [review]
Very good!

**Pull request merged**
